apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-service-list-binding
  namespace: p1
subjects:
  - kind: ServiceAccount
    name: prometheus # Ensure this matches the ServiceAccount used by Prometheus
    namespace: p1
roleRef:
  kind: Role
  name: prometheus-service-list
  apiGroup: rbac.authorization.k8s.io

