apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: static-webpage-monitor
  namespace: p1
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: static-webpage  
  endpoints:
    - port: http 
      path: /metrics
      interval: 15s
      relabelings:
        - sourceLabels: [app] 
          action: replace
          targetLabel: app
        - sourceLabels: [namespace]
          action: replace
          targetLabel: namespace
  namespaceSelector:
    matchNames:
      - p1
