apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: static-webpage-monitor
  namespace: p1
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: static-webpage
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      relabelings:
        - sourceLabels: [__meta_kubernetes_pod_labels_app]
          action: replace
          targetLabel: app
        - sourceLabels: [__meta_kubernetes_namespace]
          action: replace
          targetLabel: namespace
  namespaceSelector:
    matchNames:
      - p1
