apiVersion: v1
kind: Service
metadata:
  name: static-webpage-service
  namespace: p1
  labels:
    app: static-webpage
spec:
  selector:
    app: static-webpage
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: NodePort

